config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :books
  resources :highlights, only: ['index', 'destroy', 'update'] do
    resources :hi_tags, only: ['new', 'create']
  end
  resources :hi_tags, only: ['destroy']
  resources :tags, only: ['index', 'new', 'create', 'edit', 'update', 'destroy', 'destroy_all']
  resources :users, only: ['show', 'index'] do
    resources :books, only: ['show'], as: "friend_books"
  end

  get "friends/:id", to: "users#friends_profile", as: "friend"
  get "import", to: "highlights#import"
  post "upload", to: "highlights#upload"

  get "dashboard", to: "users#dashboard"
  get "manage", to: "books#manage"
  get "tags/manage", to: "tags#manage"
  get "friends/:user_id/books/:id", to: "books#friends_show", as: "friend_books"

  patch "follow/:id", to: "users#follow", as: "follow"
  patch "book/:id/cover", to: "books#set_parsed_cover", as: "parse_cover"
  patch "book/:id/random-cover", to: "books#random_cover", as: "random_cover"

  get "parse", to: "books#set_parsed_cover_for_all"

  # Redirects user after succesful login
  get '/user' => "books#index", :as => :user_root
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tags
  has_many :highlights
  has_many :books
  has_one_attached :photo
  acts_as_favoritor
  acts_as_favoritable

  include PgSearch::Model
  pg_search_scope :search_by_user_name,
    against: [ :first_name, :last_name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_highlight, only: ['destroy', 'update']
  before_action :set_user, only: ['follow', 'show', 'friends_profile', 'edit', 'update']

  def show
  end

  def friends_profile
  end

  def index
    if params[:query].present?
      sql_query = <<~SQL
        users.first_name @@ :query
        OR users.last_name @@ :query
      SQL
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
    @users = User.all
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def follow
    if current_user.favorited?(@user)
      current_user.unfavorite(@user)
    else
      current_user.favorite(@user)
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password, :photo)
  end
end

app/views/users/dashboard.html.erb
<div class="container">
  <div class="container d-flex justify-content-center" id="dashboard-user-info">
    <div class="avatar-img">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "avatar-profile" %>
      <% else %>
        <%= image_tag "avatar.png", class: "avatar-profile" %>
      <% end %>
    </div>
    <div class="profile-information">
      <div id="dashboard-name"><%= current_user.first_name %> <%= current_user.last_name %></div>
      <%= current_user.email %><br><br>

      <br><br>
      User since: <%= current_user.created_at.strftime("%b.%d.%Y") %><br>
      <a href="/users/edit">Update Profile Information</a>
    </div>
  </div>
  <div class="container d-flex justify-content-center">
    <div class="other-information">
        <div class="asset-count" id="book">
          <i class="fa-solid fa-book"></i>
          <h4>Books</h4>
          <p><%= current_user.books.count %></p>
          <a href="/manage" class="manage">Manage Books</a>
        </div>
        <div class="asset-count" id="highlight">
          <i class="fa-regular fa-bookmark"></i>
          <h4>Highlights</h4>
          <p><%= current_user.highlights.count %></p>
          <h4 id="fav-highlights">Favorited: <%= Favorite.for_favoritor(current_user).where(favoritable_type: "Highlight").count %></h4>
          <%# <a href="/tags/highlights" class="manage">See favorites</a> %>
        </div>
        <div class="asset-count" id="tag">
          <i class="fa-solid fa-tag"></i>
          <h4>Tags</h4>
          <p><%= current_user.tags.count %></p>
          <a href="/tags/manage" class="manage">Manage Tags</a>
        </div>
    </div>
      <div class="news">
        <div class="recent-activity" id="social">
          <h4>Your Friends</h4>
          Following : <%= Favorite.for_favoritor(current_user).where(favoritable_type: "User").count%><br>
          Followers : <%= Favorite.for_favoritable(current_user).where(favoritable_type: "User").count%><br>
          <a href="/users/<%=current_user.id%>" class="manage"><i class="fa-solid fa-arrow-right"></i>  See my social profile</a>
        </div>
        <div class="recent-activity">
          <h4>Your Recent Activity</h4>
          <ul><% current_user.books.last(5).each do |book| %>
            <li class="recent-activity-spacing"><strong><%= link_to book.title, book_path(book) %></strong>, <%= book.author.name %><br>
            Updated: <em><%=book.updated_at.strftime("%b.%d.%Y")%> at <%= book.updated_at.strftime("%I:%M%P")%></em></li>
          <% end %></ul>
        </div>
      </div>
  </div>
</div>

app/views/users/friends_profile.html.erb
  <div class="container-profile">
  <br>
  <a href="/users" class="back-friend-index"><i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back</a>
    <div class="header d-flex">
        <div class="avatar-img">
          <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, class: "avatar-profile" %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar-profile" %>
          <% end %>
        </div>
        <div class="profile-information">
          <h4><%= @user.first_name %> <%= @user.last_name %></h4>
          <p>Books in Library: <%= @user.books.count %><br>
          Highlights: <%= @user.highlights.count %><br>
          Following : <%= Favorite.for_favoritor(@user).where(favoritable_type: "User").count%>&nbsp;&nbsp; | &nbsp;
          Followers : <%= Favorite.for_favoritable(@user).where(favoritable_type: "User").count%> &nbsp;&nbsp; | &nbsp;
          <%= link_to follow_path(@user), data: {turbo_method: :patch } do %>
                <% if current_user.favorited?(@user) %>
                  <input type="submit" name="commit" value="Unfollow">
                <% else %>
                  <input type="submit" name="commit" value="+ Follow ">
                <% end %>
              <% end %>
        </div><br></p>
        <hr class="hr m-4" />
        <div class="profile-information-actions">
        </div>
    </div>
    <div class="recently-added">
      <div class="cards-added">
        <% @user.books.each do |my_book| %>
          <%= link_to friend_books_path(@user, my_book), class:"text-decoration-none cards-clickable d-flex justify-content-center" do %>
            <div class="card-book recent">
              <% if my_book.cover.attached? %>
                <%= cl_image_tag my_book.cover.key, crop: :fill %>
              <% else %>
                <%= image_tag "covers/cover-#{my_book.default_cover}.png", id: "book-cover-show" %>
              <% end %>
              <div class="card-book-recently-added">
                <h4> <%= my_book.title %> </h4>
                <p> <%= my_book.author.name %> </p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container">
  <%= render "shared/searchusers" %></div><br>
  <div class="container-social mb-5">
    <a href="/users/<%=current_user.id%>" class="back text-decoration-none"><i class="fa-regular fa-user"></i>&nbsp;&nbsp;See my social profile</a>
    <% @users.each do |user| %>
      <div class="d-flex">
      <%= link_to friend_path(user) do %>
        <div class="cards-social d-flex">
          <div class="cards-social-avatar">
              <% if user.photo.attached? %>
                <%= cl_image_tag user.photo.key, class: "avatar-social" %>
              <% else %>
                <%= image_tag "avatar.png", class: "avatar-social" %>
              <% end %>
          </div>
          <div class="cards-social-content d-flex justify-content-between align-items-center">
            <div class="cards-social-user-info">
              <h4><%= user.first_name %> <%= user.last_name %></h4>
              <p> Books: <%= user.books.count %> &nbsp;&nbsp; |
              &nbsp;&nbsp; Highlights: <%= user.highlights.count %> </p>
                Recent books: <% user.books.last(3).each do |book| %>
                  <p class="user-books"> <%= book.title %> -</p>
                <% end %>
            </div>
            <div class="friend-follow">
              <%= link_to follow_path(user), data: {turbo_method: :patch } do %>
                <% if current_user.favorited?(user) %>
                  <input type="submit" name="commit" value="Unfollow">
                <% else %>
                  <input type="submit" name="commit" value="+ Follow">
                <% end %>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container-profile">
    <div class="header d-flex">
        <div class="avatar-img">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar-profile" %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar-profile" %>
          <% end %>
        </div>
        <div class="profile-information">
          <h4><%= current_user.first_name %> <%= current_user.last_name %></h4>
          <p>Books in Library: <%= current_user.books.count %><br>
          Highlights: <%= current_user.highlights.count %><br>
          Following : <%= Favorite.for_favoritor(current_user).where(favoritable_type: "User").count%>&nbsp;&nbsp; | &nbsp;
          Followers : <%= Favorite.for_favoritable(current_user).where(favoritable_type: "User").count%><br></p>

        </div>
        <hr class="hr m-4" />
        <div class="profile-information-actions">
        </div>
    </div>
    <div class="recently-added">
      <div class="cards-added">
        <% current_user.books.each do |my_book| %>
          <%= link_to friend_books_path(current_user, my_book), class:"text-decoration-none cards-clickable d-flex justify-content-center" do %>
            <div class="card-book recent">
              <% if my_book.cover.attached? %>
                <%= cl_image_tag my_book.cover.key, crop: :fill %>
              <% else %>
                <%= image_tag "covers/cover-#{my_book.default_cover}.png", id: "book-cover-show" %>
              <% end %>
              <div class="card-book-recently-added">
                <h4> <%= my_book.title %> </h4>
                <p> <%= my_book.author.name %> </p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>