config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :books
  resources :highlights, only: ['index', 'destroy', 'update'] do
    resources :hi_tags, only: ['new', 'create']
  end
  resources :hi_tags, only: ['destroy']
  resources :tags, only: ['index', 'new', 'create', 'edit', 'update', 'destroy', 'destroy_all']
  resources :users, only: ['show', 'index'] do
    resources :books, only: ['show'], as: "friend_books"
  end

  get "friends/:id", to: "users#friends_profile", as: "friend"
  get "import", to: "highlights#import"
  post "upload", to: "highlights#upload"

  get "dashboard", to: "users#dashboard"
  get "manage", to: "books#manage"
  get "tags/manage", to: "tags#manage"
  get "friends/:user_id/books/:id", to: "books#friends_show", as: "friend_books"

  patch "follow/:id", to: "users#follow", as: "follow"
  patch "book/:id/cover", to: "books#set_parsed_cover", as: "parse_cover"
  patch "book/:id/random-cover", to: "books#random_cover", as: "random_cover"

  get "parse", to: "books#set_parsed_cover_for_all"

  # Redirects user after succesful login
  get '/user' => "books#index", :as => :user_root
end

app/views/shared/_banner.html.erb
<div class="banner">
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-links">
  <a href="#"><i class="fa-solid fa-heart"></i><small> &nbsp;&nbsp;Lucas, Leo & Soline</small></a>
  <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
    <small>hi-light&nbsp; <i class="fa-solid fa-user-group"></i></small>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar navbar-expand-sm navbar-light navbar-logo">
    <%= link_to user_signed_in? ? "/books" : "/", class: "navbar-brand" do %>
      <%= image_tag "logo-clipart.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <a href="/import"><i class="fa-solid fa-upload"></i> Import</a>
          </li>
          <li class="nav-item active">
            <a href="/books"><i class="fa-solid fa-book"></i> My Library</a>
          </li>
          <%# <li class="nav-item active">
            <a href="#"><i class="fa-solid fa-wand-magic-sparkles"></i> Rediscover</a>
          </li> %>
          <li class="nav-item active">
            <a href="/users"><i class="fa-regular fa-face-smile-beam"></i></i> Friends</a>
          </li>
          <%# <li class="nav-item active">
            <a href="#"><i class="fa-regular fa-user"></i> Me</a>
          </li> %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Settings", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "new nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="container-searchbar d-flex justify-content-center">
  <div class="search-by-buttons">
    <a href="/books"><i class="fa-solid fa-book"></i></a>
    <a href="/tags"><i class="fa-solid fa-tag"></i></a>
    <a href="/highlights"><i class="fa-solid fa-quote-left"></i></a>
  </div>
  <div class="d-row">
      <div class="search">
        <%= form_with url: books_path, method: :get, class: "d-flex" do %>
          <div class="search-form-control form-group">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search by book, author, tag or quote..."
            %>
            <button type="submit" class= "submit-btn"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_searchbooks.html.erb
<div class="container-searchbar d-flex justify-content-center">
  <div class="search-by-buttons">
    <a href="/books"><i class="fa-solid fa-book active"></i></a>
    <a href="/tags"><i class="fa-solid fa-tag"></i></a>
    <a href="/highlights"><i class="fa-solid fa-quote-left"></i></a>
  </div>
  <div class="d-row">
    <div class="search">
      <%= form_with url: books_path, method: :get, class: "d-flex" do %>
        <div class="search-form-control form-group">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by book"
          %>
          <button type="submit" class= "submit-btn"><i class="fas fa-search"></i></button>
        </div>
      <% end %>
    </div>
  </div>
  <div class="search-by-buttons">
    <%# <i data-action="click->booksindex#metadata" class="fa-regular fa-image"></i> %>
    <a href="/parse"><i class="fa-regular fa-image"></i></a>
  </div>
</div>

app/views/shared/_searchinbook.html.erb
<div class="container-searchbar d-flex justify-content-center">
  <div class="d-row">
      <div class="search">
        <%= form_with url: book_path(@book), method: :get, class: "d-flex" do %>
          <div class="search-form-control form-group">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search by highlights"
            %>
            <button type="submit" class= "submit-btn"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_searchquotes.html.erb
<div class="container-searchbar d-flex justify-content-center">
  <div class="search-by-buttons">
    <a href="/books"><i class="fa-solid fa-book"></i></a>
    <a href="/tags"><i class="fa-solid fa-tag"></i></a>
    <a href="/highlights"><i class="fa-solid fa-quote-left active"></i></a>
  </div>
  <div class="d-row">
      <div class="search">
        <%= form_with url: highlights_path, method: :get, class: "d-flex" do %>
          <div class="search-form-control form-group">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search by highlights"
            %>
            <button type="submit" class= "submit-btn"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_searchtags.html.erb
<div class="container-searchbar d-flex justify-content-center">
  <div class="search-by-buttons">
    <a href="/books"><i class="fa-solid fa-book"></i></a>
    <a href="/tags"><i class="fa-solid fa-tag active"></i></a>
    <a href="/highlights"><i class="fa-solid fa-quote-left"></i></a>
  </div>
  <div class="d-row">
      <div class="search">
        <%= form_with url: tags_path, method: :get, class: "d-flex" do %>
          <div class="search-form-control">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search by tag"
            %>
            <button type="submit" class= "submit-btn"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_searchusers.html.erb
<div class="container-searchbar d-flex justify-content-center">
  <div class="d-row">
    <div class="search">
        <%= form_with url: users_path, method: :get, class: "d-flex" do %>
          <div class="search-form-control">
            <%= text_field_tag :query,
              params[:query],
              class: "form-control tag-card",
              placeholder: "Find your friends"
            %>
            <button type="submit" class= "submit-btn"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>
  </div>
</div>