config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :books
  resources :highlights, only: ['index', 'destroy', 'update'] do
    resources :hi_tags, only: ['new', 'create']
  end
  resources :hi_tags, only: ['destroy']
  resources :tags, only: ['index', 'new', 'create', 'edit', 'update', 'destroy', 'destroy_all']
  resources :users, only: ['show', 'index'] do
    resources :books, only: ['show'], as: "friend_books"
  end

  get "friends/:id", to: "users#friends_profile", as: "friend"
  get "import", to: "highlights#import"
  post "upload", to: "highlights#upload"

  get "dashboard", to: "users#dashboard"
  get "manage", to: "books#manage"
  get "tags/manage", to: "tags#manage"
  get "friends/:user_id/books/:id", to: "books#friends_show", as: "friend_books"

  patch "follow/:id", to: "users#follow", as: "follow"
  patch "book/:id/cover", to: "books#set_parsed_cover", as: "parse_cover"
  patch "book/:id/random-cover", to: "books#random_cover", as: "random_cover"

  get "parse", to: "books#set_parsed_cover_for_all"

  # Redirects user after succesful login
  get '/user' => "books#index", :as => :user_root
end

app/models/book.rb
require "json"
require "open-uri"

class Book < ApplicationRecord
  belongs_to :author
  belongs_to :user
  has_many :highlights, dependent: :destroy
  validates :title, presence: true
  # validates :title, uniqueness: { scope: :author } # TODO add scope user
  has_one_attached :cover

  # Set default cover before creation of new book
  before_create :set_default_cover

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :title ],
    associated_against: {
      author: [ :name ],
      highlight: [ :quote ]
    },
    using: {
      tsearch: { prefix: true }
    }

  def set_default_cover
    self.default_cover = (1..96).to_a.sample
  end

  def parse_cover
    search = "#{self.title} #{self.author.name}"
    query = search.match(/(?<query>[\S ]+)[.:;?|]*/)[:query].parameterize
    url = "https://www.googleapis.com/books/v1/volumes?q=#{query}"
    data = JSON.parse(URI.open(url).read)
    if data
      return unless data["items"]
      return unless data["items"][0]["volumeInfo"]

      description = data["items"][0]["volumeInfo"]["description"]
      self.description = description[0,500] + "…" if description

      published_date = data["items"][0]["volumeInfo"]["publishedDate"]
      self.published_date = published_date.match(/^[\d]{4}/)[0] if published_date
      self.save

      return unless data["items"][0]["volumeInfo"]["imageLinks"]

      image_url = data["items"][0]["volumeInfo"]["imageLinks"]["thumbnail"]
      return unless image_url

      self.cover.attach(io: URI.open(image_url), filename: "cover.jpeg", content_type: "image/jpeg")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  before_action :set_book, only: ['destroy', 'edit', 'update', 'set_parsed_cover', 'random_cover', 'friends_show']

  def index
    if params[:query].present?
      sql_query = <<~SQL
      books.title @@ :query
      OR authors.name @@ :query
      SQL
      @books = Book.includes(:author)
        .where(sql_query, query: "%#{params[:query]}%")
        .and(Book.where(user: current_user)).order(:title).with_attached_cover
    else
      @books = Book.includes(:author).where(user: current_user).order(:title).with_attached_cover
      # flash.now[:notice] = "You have exactly #{@books.size} books in your library."
    end
  end

  def show
    @book = Book.find(params[:id])
    if params[:query].present?
      sql_query = <<~SQL
        highlights.quote @@ :query
      SQL
      @highlights = @book.highlights
        .where(sql_query, query: "%#{params[:query]}%")
    else
      @highlights = @book.highlights
    end
  end

  def friends_show
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @book.destroy
    redirect_back(fallback_location: root_path)
  end

  def set_parsed_cover
    @book.parse_cover
    @book.save
    redirect_to book_path(@book)
  end

  def set_parsed_cover_for_all
    counter = 0
    current_user.books.order(:title).each do |book|
      unless book.cover.attached?
        book.parse_cover
        book.save
        counter += 1
      end
      break if counter >= 3
    end
    redirect_to books_path
  end

  def random_cover
    @book.cover.purge
    @book.set_default_cover
    @book.save
    redirect_to book_path(@book)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def books_params
    params.require(:books).permit(:position)
  end

  def book_params
    params.require(:book).permit(:cover)
  end
end

app/views/books/edit.html.erb
<div class="container p-5 m-5">
  <h3>Update Book Cover :</h3>
  <%= simple_form_for(@book) do |f| %>
    <br>
    <%= f.input :cover, as: :file %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/books/friends_show.html.erb
<div class="wrapper">
  <div class="sidebar">
    <div class="friend-profile-link" id="friend-box">
      <div class="avatar-book-img">
        <% @user = User.find(params[:user_id]) %>
          <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, class: "avatar-book" %>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar-book" %>
          <% end %>
      </div>
      <div class="user-name">
        <%= @user.first_name %> <%= @user.last_name %><br>
        <a href="/friends/<%=@user.id%>" class="back text-decoration-none"><i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;Back</a>
      </div>
    </div>
    <div class="friend-profile-link">
      <div class="friend-book-cover">
        <% if @book.cover.attached? %>
          <%= cl_image_tag @book.cover.key, crop: :fill %>
        <% else %>
          <%= image_tag "covers/cover-#{@book.default_cover}.png", id: "book-cover-show" %>
        <% end %>
      </div>
      <div class="friend-book-info">
        <h2><%= @book.title %></h2>
        <h5><%= @book.author.name %><%= @book.published_date ? " (#{@book.published_date})" : ""%></h5>
      </div>
    </div>
  </div>

  <div class="main">
    <div class="col-sm">
      <div class="container-quotes mb-5">
        <% @book.highlights.each do |highlight| %>
          <div class="cards-quotes" data-controller="clip">
            <i class="quotes fa-solid fa-quote-left"></i>
            <div class="card-quote-content">
              <p class="" data-clip-target="item"><%= highlight.quote %> </p>
              <h5 class="d-flex justify-content-end"> p. <%= highlight.page %> </h5>
              <i class="fe fe-heart"></i>
            </div>
            <div class="cards-quotes-actions d-flex justify-content-between">
              <div class="tags d-inline-flex">
              </div>
              <div class="icons">
                <i data-action="click->clip#copy" class="icon fa-regular fa-clone"></i>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div data-controller="scroll-progress booksindex" class="h-2 bg-indigo-400 fixed top-0">
    <%= render "shared/searchbooks" %>
    <div class="cards">
      <% @books.each do |book| %>
        <%= link_to book_path(book), class:"text-decoration-none cards-clickable d-flex justify-content-center" do  %>
          <div class="card-book">
            <% if book.cover.attached? %>
              <%= cl_image_tag book.cover.key, crop: :fill %>
            <% else %>
              <%= image_tag "covers/cover-#{book.default_cover}.png" %>
            <% end %>
              <h4> <%= book.title %> </h4>
              <p> <%= book.author.name %> </p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/manage.html.erb
<div class="container justify-content-center">
  <table>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Author</th>
      <th class="table-number">Highlights</th>
      <th class="table-number">Created</th>
      <th class="table-number">Updated</th>
      <th class="table-number">Remove</th>
      <th class="table-number">Edit</th>
    </tr>
    <% current_user.books.each do |book| %>
      <tr>
        <td>
        <% if book.cover.attached? %>
          <%= cl_image_tag book.cover.key, crop: :fill, id: "book-cover-manage" %>
        <% else %>
          <%= image_tag "covers/cover-#{book.default_cover}.png", id: "book-cover-manage" %>
        <% end %></td>
        <td><%= link_to book.title, book_path(book), id:"title"%></td>
        <td><%= book.author.name %></td>
        <td class="table-number"><%= book.highlights.count %></td>
        <td class="table-number"><%= book.updated_at.strftime("%m/%d/%Y") %></td>
        <td class="table-number"><%= book.created_at.strftime("%m/%d/%Y") %></td>
        <td class="table-number"><%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, book, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
        <td class="table-number"><%= link_to '<i class="fa-regular fa-pen-to-square"></i>'.html_safe, edit_book_path(book) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/books/show.html.erb
<div class="container-main">
  <div class="d-flex justify-content-center align-items-center mt-5">
      <div class="book-cover">
        <% if @book.cover.attached? %>
          <%= cl_image_tag @book.cover.key, crop: :fill %>
        <% else %>
          <%= image_tag "covers/cover-#{@book.default_cover}.png", id: "book-cover-show" %>
        <% end %>
        <div class="book-cover-links">
          <%= link_to parse_cover_path(@book), data: {turbo_method: :patch} do %>
            <i class="fa-solid fa-book"></i><span>Download</span>
          <% end %>
          <%= link_to random_cover_path(@book), data: {turbo_method: :patch } do %>
            <i class="fa-solid fa-shuffle"></i><span>Random</span>
          <% end %>
        </div>
      </div>
      <div class="book-info">
        <h2><%= @book.title %></h2>
        <h5><%= @book.author.name %><%= @book.published_date ? " (#{@book.published_date})" : ""%></h5>
        <p><%= @book.description ? @book.description : "" %></p>
        <div id="highlight-no"> <%= pluralize(@book.highlights.count, 'highlight') %></div>
      </div>
  </div>

  <%= render "shared/searchinbook" %></div><br>
  <div class="container-quotes mb-5">
    <% @highlights.each do |highlight| %>
      <div class="cards-quotes" data-controller="clip">
        <i class="quotes fa-solid fa-quote-left"></i>
        <div class="card-quote-content">
          <p class="" data-clip-target="item"><%= highlight.quote %> </p>
          <h5 class="d-flex justify-content-end"> p. <%= highlight.page %> </h5>
          <i class="fe fe-heart"></i>
        </div>
        <div class="cards-quotes-actions d-flex justify-content-between" data-controller="edit-tag">
          <div class="tags d-inline-flex">
            <% highlight.tags.each do |tag| %>
            <div class="tag-card text-decoration-none">
                <div class="<%=tag.color%> x-pic">
                  <%# <%= link_to hi_tag_path(highlight.hi_tags.where(tag: tag).pluck(:id)), data: {turbo_method: :delete, turbo_confirm: "Do you want to delete it?", id:"delete", class:"text-decoration-none"} do %>
                    <%# <div class="editt"><i class="fa-regular fa-circle-xmark"></i></div> %>
                  <%# <% end %>
                  <a class="text-decoration-none tag-no-hover" href="/tags?query=<%=tag.name %>">
                    <p class="tag-no-hover"><%= tag.name %></p>
                  </a>
                </div>
            </div>
            <% end %>
          </div>

          <%= simple_form_for [highlight, HiTag.new], class: "form", html: {class: "d-none form-inline", data: {edit_tag_target:"form"}} do |f| %>
            <div class="flexbox-class">
              <%= f.input :tag, label: false, collection: current_user.tags, include_hidden: false, wrapper_html: {class: "mb-0"}  %>
              <%= f.submit "+", class: 'add-tag' %>
            </div>
          <% end %>

          <div class="icons">
            <i class="icon fa-solid fa-tag" data-action="click->edit-tag#displayForm"></i>
            <%= link_to highlight_path(highlight, book: @book), data: {turbo_method: :patch } do %>
              <% if current_user.favorited?(highlight) %>
                <i class="icon fa-solid fa-heart" id="favorite-heart"></i>
              <% else %>
                <i class="icon fa-regular fa-heart"></i>
              <% end %>
            <% end %>
            <%= link_to highlight_path(highlight, book: @book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?", id:"delete"} do %>
              <i class="icon fa-regular fa-trash-can"> </i>
            <% end %>
            <i data-action="click->clip#copy" class="icon fa-regular fa-clone"></i>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>