config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :books
  resources :highlights, only: ['index', 'destroy', 'update'] do
    resources :hi_tags, only: ['new', 'create']
  end
  resources :hi_tags, only: ['destroy']
  resources :tags, only: ['index', 'new', 'create', 'edit', 'update', 'destroy', 'destroy_all']
  resources :users, only: ['show', 'index'] do
    resources :books, only: ['show'], as: "friend_books"
  end

  get "friends/:id", to: "users#friends_profile", as: "friend"
  get "import", to: "highlights#import"
  post "upload", to: "highlights#upload"

  get "dashboard", to: "users#dashboard"
  get "manage", to: "books#manage"
  get "tags/manage", to: "tags#manage"
  get "friends/:user_id/books/:id", to: "books#friends_show", as: "friend_books"

  patch "follow/:id", to: "users#follow", as: "follow"
  patch "book/:id/cover", to: "books#set_parsed_cover", as: "parse_cover"
  patch "book/:id/random-cover", to: "books#random_cover", as: "random_cover"

  get "parse", to: "books#set_parsed_cover_for_all"

  # Redirects user after succesful login
  get '/user' => "books#index", :as => :user_root
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :hi_tags, dependent: :destroy
  has_many :highlights, through: :hi_tags
  validates :name, presence: true, uniqueness: { scope: :user }
  validates :name, length: { maximum: 16, message: "max of 16 characters" }

  include PgSearch::Model
  pg_search_scope :search_by_tag_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_tag, only: [:edit, :update, :destroy, :destroy_all]

  def index
    @tags = Tag.where(user: current_user)
    if params[:query].present?
      sql_query = <<~SQL
        tags.name @@ :query
        OR tags.name ILIKE :query
      SQL
      search_tags = Tag.where(sql_query, query: "%#{params[:query]}%").and(Tag.where(user: current_user)).pluck(:name)
      @highlights = Highlight.joins(:tags).where(tags: { name: search_tags }).and(Highlight.where(user: current_user)).distinct
    else
      @highlights = nil
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user
    if @tag.save
      redirect_to tags_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @tag.update(tag_params)

    respond_to do |format|
      format.html { redirect_to tags_manage_path }
      format.text { render partial: "tags/tag-infos", locals: {tag: @tag}, formats: [:html] }
    end
  end

  def destroy
    @tag.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :color)
  end
end

app/views/tags/_tag-infos.html.erb
<td data-edit-tag-target="tagInfo"><span class="tag-index">
  <a href="/tags?query=<%=tag.name %>">
    <button class="<%= tag.highlights.empty? ? 'none' : tag.color %>">
      <%= tag.name %></span>
    </button>
  </a>
</td>

app/views/tags/edit.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.input :name %>
  <%= f.input :color, collection: %w[blue purple orange yellow red green] %>
  <%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<div class="container">
  <%= render "shared/searchtags" %><br>
  <div class="container-tags">
    <div class="tags-container">
      <% current_user.tags.each do |tag| %>
        <div class="tag-index">
          <a href="?query=<%=tag.name %>">
            <button class="<%= tag.highlights.empty? ? 'none' : tag.color %>">
              <%= tag.name %>
            </button>
          </a>
        </div>
      <% end %>
    </div>
  </div>
  <div class="tag-search-results">
    <div class="container-quotes mb-5">
      <% if !@highlights.nil? %>
        <% @highlights.each do |highlight| %>
                <div class="cards-quotes" data-controller="clip">
                    <i class="quotes fa-solid fa-quote-left"></i>
                    <div class="card-quote-content">
                      <p class="" data-clip-target="item"><%= highlight.quote %> </p>
                      <h5 class="d-flex justify-content-end"><%= highlight.book.title %> - p. <%= highlight.page %> </h5>
                    </div>
                    <div class="cards-quotes-actions d-flex justify-content-between" data-controller="edit-tag">
                      <div class="tags d-inline-flex">
                        <% highlight.tags.each do |tag| %>
                        <div class="tag-card text-decoration-none">
                          <div class="<%=tag.color%> x-pic">
                            <%= link_to hi_tag_path(highlight.hi_tags.where(tag: tag).pluck(:id)), data: {turbo_method: :delete, turbo_confirm: "Do you want to delete it?", id:"delete", class:"text-decoration-none"} do %>
                              <div class="editt"><i class="fa-regular fa-circle-xmark"></i></div>
                            <% end %>
                          <p><%= tag.name %></p>
                          </div>
                        </div>
                        <% end %>
                      </div>

                        <%= simple_form_for [highlight, HiTag.new], class: "form", html: {class: "d-none form-inline", data: {edit_tag_target:"form"}} do |f| %>
                        <div class="flexbox-class">
                          <%= f.input :tag, label: false, collection: current_user.tags, include_hidden: false, wrapper_html: {class: "mb-0"}  %>
                          <%= f.submit "+", class: 'add-tag' %>
                        </div>
                        <% end %>

                      <div class="icons">
                        <i class="icon fa-solid fa-tag" data-action="click->edit-tag#displayForm"></i>
                        <%= link_to highlight_path(highlight, book: @book), data: {turbo_method: :patch } do %>
                          <% if current_user.favorited?(highlight) %>
                            <i class="icon fa-solid fa-heart" id="favorite-heart"></i>
                          <% else %>
                            <i class="icon fa-regular fa-heart"></i>
                          <% end %>
                        <% end %>

                        <%= link_to @highlight, data: {turbo_method: :delete, turbo_confirm: "Are you sure?", id:"delete"} do %>
                          <i class="icon fa-regular fa-trash-can"> </i>
                        <% end %>
                        <i data-action="click->clip#copy" class="icon fa-regular fa-clone"></i>
                      </div>
                    </div>
                </div>
        <% end %>
      <% end %>
      <a class="top-link hide" href="" id="js-top">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6"><path d="M12 6H0l6-6z"/></svg>
        <span class="screen-reader-text">Back to top</span>
      </a>
    </div>
  </div>
</div>

<script>
const scrollToTopButton = document.getElementById('js-top');
const scrollFunc = () => {
  // Get the current scroll value
  let y = window.scrollY;

  // If the scroll value is greater than the window height, let's add a class to the scroll-to-top button to show it!
  if (y > 0) {
    scrollToTopButton.className = "top-link show";
  } else {
    scrollToTopButton.className = "top-link hide";
  }
};

window.addEventListener("scroll", scrollFunc);

const scrollToTop = () => {
  // Let's set a variable for the number of pixels we are from the top of the document.
  const c = document.documentElement.scrollTop || document.body.scrollTop;

  // If that number is greater than 0, we'll scroll back to 0, or the top of the document.
  // We'll also animate that scroll with requestAnimationFrame:
  // https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
  if (c > 0) {
    // window.requestAnimationFrame(scrollToTop);
    // ScrollTo takes an x and a y coordinate.
    // Increase the '10' value to get a smoother/slower scroll!
    window.scrollTo(0, c - c / 1);
  }
};

// When the button is clicked, run our ScrolltoTop function above!
scrollToTopButton.onclick = function(e) {
  e.preventDefault();
  scrollToTop();
}
</script>

app/views/tags/manage.html.erb
<div class="container d-flex justify-content-center">
  <div class="tags-index-manage">
  <h4> All your tags <small><em> (<%=current_user.tags.count%>)</small><em></h4>
    <% current_user.tags.each do |tag| %>
      <span class="tag-index">
      <a href=""><button class="<%= tag.highlights.empty? ? 'none' : tag.color %>">
        <%= tag.name %></span>
      </button></a>
    <% end %>
  </div>
</div>
<button class="new-tag-button"><%= link_to  '<i class="fa-solid fa-plus"></i> Create a new tag'.html_safe, new_tag_path, id:"new-tag-text"%></button>

<div class="container justify-content-center">
  <div class="tags-table" data-edit-tag-target="infos">
    <table>
      <tr>
        <th class="table-number">Tag</th>
        <th class="table-number">Highlight Count</th>
        <th class="table-number">Delete</th>
        <th colspan="2" class="table-number">Edit</th>
      </tr>
      <% current_user.tags.each do |tag| %>
        <tr data-controller="edit-tag">
          <%= render "tag-infos", tag: tag %>
          <td class="table-number"><%= tag.highlights.count %></td>
          <td class="table-number"><%= link_to  '<i class="fa-regular fa-trash-can"></i>'.html_safe, tag, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
          <td class="table-number"><button class="edit-tag-button"><i class="fa-regular fa-pen-to-square" data-action="click->edit-tag#displayForm"></i></button></td>
          <td><%= simple_form_for tag, html: {class: "d-none", data: {edit_tag_target:"form", action: "submit->edit-tag#update"}} do |f| %>
            <%= f.input :name %>
            <%= f.input :color, collection: %w[blue purple orange yellow red green] %>
            <%= f.submit %>
          <% end %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/tags/new.html.erb
<div class="container">
<br><br>
<h4>Create a new tag:</h4>
<br><br>
  <%= simple_form_for(@tag) do |f| %>
    <%= f.input :name %>
    <%= f.input :color, collection: %w[blue purple orange yellow red green] %>
    <%= f.submit %>
  <% end %>
</div>